language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.8.7
  - DJANGO_VERSION=1.9
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install path.py
script: python mail_templated/tests/runtests.py
