language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.8.15
  - DJANGO_VERSION=1.9.9
  - DJANGO_VERSION=1.10.1
  - DJANGO_VERSION=1.11
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install path.py
script: python mail_templated/tests/runtests.py
