language: python
python:
  - "3.4"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION=1.8.15
  - DJANGO_VERSION=1.9.9
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.2.9
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install path
script: python mail_templated/tests/runtests.py
